#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 检查最后一次提交的消息
last_commit_message=$(git log -1 --pretty=%B)

# 如果最后一次提交不是更新日志，则生成更新日志并提交
if [[ "$last_commit_message" != "chore(log): 生成博客更新日志。" ]]; then
  # 尝试运行 pnpm log，如果失败（返回非0状态码），则执行 npm run log
  pnpm log || npm run log
  git add ./docs/zh/关于我/更新日志.md
  git commit -m "chore(log): 生成博客更新日志。"
fi